spring.application.name=psql

spring.datasource.url=jdbc:postgresql://localhost:5432/firstdb
spring.datasource.username=suryatk
spring.datasource.password=qazplm100
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
